namespace TaskStorm.Event;
public enum EventType
{
    ISSUE_CREATED,
    ISSUE_ASSIGNED,
    ISSUE_DELETED,
    COMMENT_CREATED,
    UPDATE_STATUS,
    UPDATE_PRIORITY,
    UPDATE_DUEDATE,
    UPDATE_ASSIGNEE,
    UPDATE_TITLE,
    UPDATE_DESCRIPTION
}
