services:
  taskstorm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskstorm-api
    restart: unless-stopped
    ports:
      - "5167:6901"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6901 
      - TS_LOG_DIR=/app/logs
      - TS_LOG_FILENAME=taskstorm
      
      - JWT__SECRET=${JWT_SECRET}
      - JWT__ISSUER=${JWT_ISSUER}
      - JWT__AUDIENCE=${JWT_AUDIENCE}
      
      - TS_DB_HOST=host.docker.internal
      - TS_DB_PORT=5432
      - TS_DB_NAME=taskstorm
      - TS_DB_USER=taskstorm 
      - TS_DB_PASSWORD=${TS_DB_PASSWORD}
      
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=taskstorm;Username=taskstorm;Password=${TS_DB_PASSWORD}
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=${TS_RABBITMQ_PASSWORD}
    volumes:
      - ./data/logs:/app/logs
      - ./data/uploads:/app/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taskstorm-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${TS_RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5672 || exit 1"]
      interval: 10s 
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq 
      - ./data/rabbitmq-logs:/var/log/rabbitmq 