namespace TaskStorm.Model.Entity;

public enum ActivityType
{
    CREATED_ISSUE,
    CREATED_COMMENT,
    CREATED_LABEL,
    DELETED_ISSUE,
    DELETED_LABEL,
    UPDATED_ASSIGNEE,
    UPDATED_PRIORITY,
    UPDATED_STATUS,
    UPDATED_TITLE,
    UPDATED_DESCRIPTION,
    UPDATED_DUEDATE,
    UPDATED_TEAM

}
